name: CI

on:

push:

branches:

- main

jobs:

  build:

    runs-on: ubuntu-latest

    name: Run tests and linters

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run lint (Run ESLint)

    - run: npm test (Run tests with Jest)
